version: '3'
services:

  nginx:
    image: 'nginx:latest'
    container_name: forum
    volumes:
      - ./public:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - codeigniter_net
    ports:
      - "8181:90"
    restart: always
    depends_on:
      - php

  php:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: forum_php
    volumes:
      - ./public:/public
    depends_on:
      - database
    networks:
      - codeigniter_net

  database:
    image: 'mysql:5.7'
    container_name: mysql_forum5.7
    environment:
      - MYSQL_ROOT_PASSWORD=ci
    networks:
      - codeigniter_net
    ports:
      - 3306:3306

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: phpmyadmin
    restart: always
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - codeigniter_net
    ports:
      - '8282:80'

networks:
  codeigniter_net:

#容器跑起来，需要使用这个命令，将文件拷贝到容器里，后重启容器
#docker cp ./config.inc.php phpmyadmin:/etc/phpmyadmin/



